
server:
  port: 8080
spring:
  application:

    name: reggie
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie
      username: root
      password: "password"

  redis:
    host: 
    port:
    password:
    database:
  cache:
    redis:
      time-to-live: 1800000 #30 mins

mybatis-plus:
  configuration:

    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: /Users/pan11/Desktop/img/
